version: 2.1

orbs:
  singularity: singularity/singularity@1.0.0

workflows:
  install_debian_3_example:
    jobs:
      - singularity/install_debian_3:
        go-version: 11.1.5
        singularity-version: 3.2.1
