version: 2.1

orbs:
  singularity: singularity/singularity@1.0.2

workflows:
  build_container_docker_base_example:
    jobs:
      - singularity/build_container_docker_base:
          from-uri: docker://busybox 
          image: busybox.sif
